version: 2

sources:
  - name: raw_fhir
    schema: raw_fhir
    tables:
      - name: patient
      - name: condition
      - name: observation
      - name: medication_request
      - name: claim
      - name: encounter
